services:
- type: web
  name: minio
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  disk:
    name: data
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
